### ISSUE TITLE
bspwm blackscreen after following the guide

### ISSUE THREAD

**Issue by JadeInTheSky** [HynDuf/dotfiles#4]
Hey, I followed the guide and when I launch bspwm from any greeter (and startx) I get a blackscreen with no shortcuts whatsoever. I've seen on multiple wikis that it is caused by a faulty shxkd but it is installed, configured, and perms are ok.

my .bashrc
[.bashrc.txt](https://github.com/HynDuf7/dotfiles/files/9610225/default.bashrc.txt)

my bspwmrc
[bspwmrc.txt](https://github.com/HynDuf7/dotfiles/files/9610230/bspwmrc.txt)

my shxkdrc
[sxhkdrc.txt](https://github.com/HynDuf7/dotfiles/files/9610231/sxhkdrc.txt)

and my journalctl
[logs.txt](https://github.com/HynDuf7/dotfiles/files/9610196/logs.txt)

if you need any other information let me know and I'll update asap

ps. really love your theme btw. One of the best I've seen on unixporn.

EDIT: syntax

**Comment by HynDuf** [comment]
Could you answer some of my questions:

- Have you installed [st](https://github.com/siduck/st) terminal? If already, does `super + Return` open any terminal?
- Have you installed `hollow-knight.png` file into `~/Pictures/`?

**Comment by JadeInTheSky** [comment]
yes to both

**Comment by HynDuf** [comment]
Try to run these in your terminal and show your outputs:

- `feh --bg-fill ~/Pictures/hollow-knight.png`
- `polybar`
