### ISSUE TITLE
bspwm not working (I think so)

### ISSUE THREAD

**Issue by YeralAndre** [HynDuf/dotfiles#5]
(Sorry for my English, I speak Spanish)
I was trying to configure the dotfile in a VirtualBox virtual machine (it should be noted that I tried to install it twice, this dotfile is beautiful, I need to install it), and I think the bspwm is not working for me. When I entered the virtual machine I did all the configuration from the console, and when I restart the machine it sends me directly to it, I don't see a graphical interface or anything similar. When using the `startx` command (I saw it on a forum), the screen goes black, I have to use the `feh --bg-fill path/to/file &` command manually to apply a background, and when I open the terminal (I use kitty), it opens usually. I have to display the `polybar` manually with `Super + X` and I can't get the correct background. Rofi shortcuts work excluding notification center, lock screen and the above mentioned. I am new to installing dotfiles, if you could guide me in any way or if there is a specific guide to installing it from scratch that would be a great help. Thank you

![image](https://user-images.githubusercontent.com/67988325/223883854-75596084-a57d-4be4-aa4a-1ae73303fd89.png)
![image](https://user-images.githubusercontent.com/67988325/223882408-0615dbf4-1869-4fab-afa5-26664014dd8e.png)
![image](https://user-images.githubusercontent.com/67988325/223884970-add648dd-b06c-4d4b-ab51-e81a6e2cd0a4.png)

**Comment by HynDuf** [comment]
Could you show me your `~/.config/bspwm/bspwmrc`? 
This file is responsible for autostarting programs when open bspwm.

Besides, as you use `startx`, in your [`.xinitrc`](https://github.com/HynDuf/dotfiles/blob/main/.xinitrc), remember to have `exec bspwm`.

**Comment by YeralAndre** [comment]
I have it this way, I don't know if it's the right one, I used the `arandr` package to adjust everything to my screen aspect ratio, 1440x900:

`~/.config/bspwm/bspwmrc`
![image](https://user-images.githubusercontent.com/67988325/223887745-ea492d8b-b81a-4311-a65c-8f9d8d653f47.png)
`.xinitrc`
![image](https://user-images.githubusercontent.com/67988325/223888203-e2a16a6d-0fdf-46f0-b531-fcab88ad2d17.png)

**Comment by HynDuf** [comment]
I don't really know what's really wrong.

Somethings to try:
- Leaving only `exec bspwm` in `.xinitrc` (move others one to `bspwmrc`). After restarting check your keyboard shortcuts (sxhkd) to see if `bspwmrc` is really executed.
- Delete the second line of your `bspwmrc` (duplicate). 
- Fix to `bspc monitor -d 1 2 3 4 5 6 7` (As I have 7 desktops in my polybar).

See if it work and show your `bspwm` and `.xinitrc` after that if it didn't.

**Comment by YeralAndre** [comment]
I made the changes, and it sends me back to the console when I start, these are my files, sorry for my ignorance, I handle the issue a bit but not 100%:

`.xinitrc`
![image](https://user-images.githubusercontent.com/67988325/223891316-b097caf7-7663-49e5-bef3-1553533fc24d.png)

`bspwmrc`
![image](https://user-images.githubusercontent.com/67988325/223891385-a32bd40e-5ced-4576-8f8f-41c080dbe76a.png)

> I don't really know what's really wrong.
> 
> Somethings to try:
> 
> * Leaving only `exec bspwm` in `.xinitrc` (move others one to `bspwmrc`). After restarting check your keyboard shortcuts (sxhkd) to see if `bspwmrc` is really executed.
> * Delete the second line of your `bspwmrc` (duplicate).
> * Fix to `bspc monitor -d 1 2 3 4 5 6 7` (As I have 7 desktops in my polybar).
> 
> See if it work and show your `bspwm` and `.xinitrc` after that if it didn't.

**Comment by HynDuf** [comment]
> I made the changes, and it sends me back to the console when I start, these are my files, sorry for my ignorance, I handle the issue a bit but not 100%:
> 
> `.xinitrc` ![image](https://user-images.githubusercontent.com/67988325/223891316-b097caf7-7663-49e5-bef3-1553533fc24d.png)
> 
> `bspwmrc` ![image](https://user-images.githubusercontent.com/67988325/223891385-a32bd40e-5ced-4576-8f8f-41c080dbe76a.png)
> 
> > I don't really know what's really wrong.
> > Somethings to try:
> > 
> > * Leaving only `exec bspwm` in `.xinitrc` (move others one to `bspwmrc`). After restarting check your keyboard shortcuts (sxhkd) to see if `bspwmrc` is really executed.
> > * Delete the second line of your `bspwmrc` (duplicate).
> > * Fix to `bspc monitor -d 1 2 3 4 5 6 7` (As I have 7 desktops in my polybar).
> > 
> > See if it work and show your `bspwm` and `.xinitrc` after that if it didn't.

There shouldn't be `startx` inside `.xinitrc`. You have to type it your own to open bspwm.

And if you don't know, people use `startx` (me too) all start up with terminal and then type `startx` to start (after logging in)

**Comment by YeralAndre** [comment]
Ok, I didn't know that, well usually in several tutorials that I saw they had a login with a graphical interface, but that would be done in another way I suppose. I've already made the changes you mentioned, and when I use `startx`, it now shows me a black screen, I can't use the shortcuts or anything like that, or open the terminal.

> There shouldn't be `startx` inside `.xinitrc`. You have to type it your own to open bspwm.
> 
> And if you don't know, people use `startx` (me too) all start up with terminal and then type `startx` to start (after logging in)

**Comment by HynDuf** [comment]
Oh so the problem might be you haven't made `bspwmrc` executable.

Try running `chmod +x ~/.config/bspwm/bspwmrc` and restart see if things work out ok. And in case you haven't, `chmod +x ~/.config/sxhkd/sxhkdrc` too.

**Comment by YeralAndre** [comment]
> Oh so the problem might be you haven't made `bspwmrc` executable.
> 
> Try running `chmod +x ~/.config/bspwm/bspwmrc` and restart see if things work out ok. And in case you haven't, `chmod +x ~/.config/sxhkd/sxhkdrc` too.

One question, do I do it as `root`? I did it as a normal user and nothing happened.

**Comment by HynDuf** [comment]
> > Oh so the problem might be you haven't made `bspwmrc` executable.
> > Try running `chmod +x ~/.config/bspwm/bspwmrc` and restart see if things work out ok. And in case you haven't, `chmod +x ~/.config/sxhkd/sxhkdrc` too.
> 
> One question, do I do it as `root`? I did it as a normal user and nothing happened.

Try do it as `root` and run `~/.config/bspwm/bspwmrc` in your terminal to see if it executes.

**Comment by YeralAndre** [comment]
> Try do it as `root` and run `~/.config/bspwm/bspwmrc` in your terminal to see if it executes.

When accessing root with `sudo su`, it seems that I don't have the directory, I did everything as a normal user, would that be the problem?

![image](https://user-images.githubusercontent.com/67988325/223894359-4e6f38b7-6c9a-4e2f-8cfb-e9c11284a351.png)

**Comment by HynDuf** [comment]
> > Try do it as `root` and run `~/.config/bspwm/bspwmrc` in your terminal to see if it executes.
> 
> When accessing root with `sudo su`, it seems that I don't have the directory, I did everything as a normal user, would that be the problem?
> 
> ![image](https://user-images.githubusercontent.com/67988325/223894359-4e6f38b7-6c9a-4e2f-8cfb-e9c11284a351.png)

Simple change the `~/.config...` to `/home/YOUR_USERNAME/.config...`.

Instead, in your user terminal (not `sudo su`), you can `sudo chmod +x ~/.config/bspwm/bspwmrc`.

**Comment by YeralAndre** [comment]
> Simple change the `~/.config...` to `/home/YOUR_USERNAME/.config...`.
> 
> Instead, in your user terminal (not `sudo su`), you can `sudo chmod +x ~/.config/bspwm/bspwmrc`.


I did what you told me with `sudo ...` and it doesn't work, I think I did something wrong in the setup, because I keep getting the black screen. 😕

**Comment by HynDuf** [comment]
Did you try running `~/.config/bspwm/bspwmrc` in your starting terminal? Take screenshots if anything happended.

**Comment by YeralAndre** [comment]
I already did, I got this error, I think it's something with the `feh` module:

![image](https://user-images.githubusercontent.com/67988325/223896588-2ab9a0ab-f4bd-4bfe-aa4e-5a5968a0bf09.png)

**Comment by HynDuf** [comment]
Hmm, the `Can't open display` is from your `...display.sh` right? Try to run it only to see if it runs.

Also, add `&` after your `...display.sh` line in `bspwmrc`.

**Comment by YeralAndre** [comment]
Using it alone gives me the same error it seems, I tried to remove that line from `bspwmrc` and run it again but it gives me the same error.

**Comment by HynDuf** [comment]
Btw, what is that of your `display.sh`. Show me the details of it.

**Comment by HynDuf** [comment]
Final tips I can give you is try following guides on Youtube (or anywhere) about installing `bspwm` on Arch on VirtualBox and make sure it really works and `bspwm` (and those display screen things) really runs. After that, use my configs then.

**Comment by YeralAndre** [comment]
> Btw, what is that of your `display.sh`. Show me the details of it.

![image](https://user-images.githubusercontent.com/67988325/223900234-cd90be7e-9575-4b9e-bedf-142f7f8c33c1.png)

**Comment by YeralAndre** [comment]
> Final tips I can give you is try following guides on Youtube (or anywhere) about installing `bspwm` on Arch on VirtualBox and make sure it really works and `bspwm` (and those display screen things) really runs. After that, use my configs then.

I was looking at everything related to it, and I managed to get it to work, only in the `.xinitrc`, that's why I resorted to your help.

**Comment by HynDuf** [comment]
> > Btw, what is that of your `display.sh`. Show me the details of it.
> 
> ![image](https://user-images.githubusercontent.com/67988325/223900234-cd90be7e-9575-4b9e-bedf-142f7f8c33c1.png)

Oh so it called `xrandr`. It should be before `exec bspwm` in `.xinitrc`. Try moving `...display.sh` back into your `.xinitrc` **before** `exec bspwm`. Run again and take screenshots of any errors poping up.

**Comment by YeralAndre** [comment]
> Oh so it called `xrandr`. It should be before `exec bspwm` in `.xinitrc`. Try moving `...display.sh` back into your `.xinitrc` **before** `exec bspwm`. Run again and take screenshots of any errors poping up.

Done, I think it's still throwing me the same errors.

`.xinitrc`
![image](https://user-images.githubusercontent.com/67988325/223901643-52d63e6f-4ade-4309-9119-ef0567aa2e68.png)

Errors:
![image](https://user-images.githubusercontent.com/67988325/223901822-ebf59c04-d423-4b8e-962a-6e1ef7efa6a8.png)

**Comment by HynDuf** [comment]
Wait try running `startx`. Take screenshots too.

**Comment by YeralAndre** [comment]
> Wait try running `startx`. Take screenshots too.

I ran `startx` and the screen resizes to the size I placed, but it's still black, I think the error still persists in `bspwmrc`.

**Comment by HynDuf** [comment]
Exit `bspwm` to see any logs/errors when running `startx`. Take screenshots of those.

**Comment by YeralAndre** [comment]
> Exit `bspwm` to see any logs/errors when running `startx`. Take screenshots of those.

No shortcuts work, it's like `sxhkd ` doesn't load the hotkeys, none work, I have to open another terminal with `Ctrl + Alt + F3` to access the console.

**Comment by HynDuf** [comment]
Run `sxhkd` in that terminal and exit current `bspwm` then do the above. Alternatively, you can `startx > output.txt` and `cat output.txt` to see the logs.

**Comment by YeralAndre** [comment]
> Run `sxhkd` in that terminal and exit current `bspwm` then do the above. Alternatively, you can `startx > output.txt` and `cat output.txt` to see the logs.

I did the former, and it looks like the `...display.sh` error was from `sxhkd`:

![image](https://user-images.githubusercontent.com/67988325/223904437-b00026f8-e1e3-4337-8634-e652139ffcb7.png)

And, by using `startx > output.txt`, it creates the empty file.

**Comment by HynDuf** [comment]
This is so weird. Replace `sxhkd &` in `bspwmrc` with `pgrep -x sxhkd > /dev/null || sxhkd &`. Restart your machine, run `startx` and see if `sxhkd` works (Assume you have already make `sxhkdrc` executable)

**Comment by YeralAndre** [comment]
> This is so weird. Replace `sxhkd &` in `bspwmrc` with `pgrep -x sxhkd > /dev/null || sxhkd &`. Restart your machine, run `startx` and see if `sxhkd` works (Assume you have already make `sxhkdrc` executable)

It still doesn't work, it keeps giving me the same `Can't open display.` error and the shortcuts don't work, it's too weird if it worked differently before.

**Comment by HynDuf** [comment]
From the Arch wiki of xinit. you may miss the last `if` block.

![image](https://user-images.githubusercontent.com/29995756/223906662-765f5784-e646-46c0-8c3f-33d18ca371fc.png)

Delete the old `.xinitrc`.
Copy `cp /etc/X11/xinit/xinitrc ~/.xinitrc`.
Add `...display.sh` and `exec bspwm` at the bottom.

Read the docs for [xinit](https://wiki.archlinux.org/title/xinit) to see if you missed anything else.

**Comment by YeralAndre** [comment]
> From the Arch wiki of xinit. you may miss the last `if` block.
> 
> ![image](https://user-images.githubusercontent.com/29995756/223906662-765f5784-e646-46c0-8c3f-33d18ca371fc.png)
> 
> Delete the old `.xinitrc`. Copy `cp /etc/X11/xinit/xinitrc ~/.xinitrc`. Add `...display.sh` and `exec bspwm` at the bottom.
> 
> Read the docs for [xinit](https://wiki.archlinux.org/title/xinit) to see if you missed anything else.

It doesn't give me an error (In the end it's `exec bspwm`, I realized it but I took the photo before, it gave me an error because of that), but I still can't execute any command it seems.

![image](https://user-images.githubusercontent.com/67988325/223908771-b0c1076b-c7ab-463f-8e10-4c6137d9ed61.png)

**Comment by HynDuf** [comment]
What do you mean by 
> "It doesn't give me an error (In the end it's exec bspwm, I realized it but I took the photo before, it gave me an error because of that), but I still can't execute any command it seems."

Any logs would be helpful

**Comment by YeralAndre** [comment]
I made the changes you mentioned, used the default `.xinitrc`, and added those last two lines, but the screen still looks dark, and no keys work, plus it still seems to throw the `Can' error t open display`.

![image](https://user-images.githubusercontent.com/67988325/223909792-3d10591d-38ea-4ada-aebe-e1f55432eea3.png)

I was checking online, does enabling the `sxhkd.service` service have anything to do with it?

**Comment by HynDuf** [comment]
Have you run `...display.sh` before calling `bspwmrc`? Try `startx` instead and show the logs.

**Comment by YeralAndre** [comment]
> Have you run `...display.sh` before calling `bspwmrc`? Try `startx` instead and show the logs.

I used `startx &> output2.txt` and now it gives me the log, I show you:
![image](https://user-images.githubusercontent.com/67988325/223911411-b765cc86-ca8e-4e1f-857b-b9b938cda697.png)

**Comment by HynDuf** [comment]
It says can't execute the configuration file. Have you `chmod +x ~/.config/bspwm/bspwmrc`. Do it again and take screenshots.

**Comment by YeralAndre** [comment]
Is it me, or does the `chmod` not take effect?

![image](https://user-images.githubusercontent.com/67988325/223912681-0a514438-72b4-4b39-a73b-ea37022ec0ff.png)

**Comment by HynDuf** [comment]
Hmm it should be fine already. Does `startx` produce the same logs?

**Comment by YeralAndre** [comment]
Yes, produce same logs, same of older screenshot.

**Comment by HynDuf** [comment]
I have no idea right now. Maybe try installing basic `bspwm` and `sxhkd` follow guides on the Internet and see if your `bspwm` still got that error.

**Comment by YeralAndre** [comment]
Hey, I made it work xD. There was a missing `#!/bin/sh ` it seems in `~/.config/bspwm/bspwmrc`, I can see the environment like this:

![image](https://user-images.githubusercontent.com/67988325/223917133-7138ba8f-6d74-43d4-bde5-ab61350facb8.png)

Seriously, sorry for wasting your time with such a useless error, can I continue writing in this Issue if I continue to have other problems?

**Comment by HynDuf** [comment]
> Hey, I made it work xD. There was a missing `#!/bin/sh ` it seems in `~/.config/bspwm/bspwmrc`, I can see the environment like this:
> 
> ![image](https://user-images.githubusercontent.com/67988325/223917133-7138ba8f-6d74-43d4-bde5-ab61350facb8.png)
> 
> Seriously, sorry for wasting your time with such a useless error, can I continue writing in this Issue if I continue to have other problems?

Yes of course 😂. Glad you fixed it. There would be more bugs to come so prepare for them.

**Comment by YeralAndre** [comment]
Haha yes, again I repeat that I fell in love with this environment at first sight, that's why I long to have it 100% to use it as the default environment.
I was checking and the upper `polybar` keeps emitting a kind of "error" referring to `pomo-format`, what is it referring to?
And I noticed that the notification center shortcut doesn't work, maybe it's due to a package, right?

**Comment by HynDuf** [comment]
> Haha yes, again I repeat that I fell in love with this environment at first sight, that's why I long to have it 100% to use it as the default environment. I was checking and the upper `polybar` keeps emitting a kind of "error" referring to `pomo-format`, what is it referring to? And I noticed that the notification center shortcut doesn't work, maybe it's due to a package, right?

Try read the README more rigorous. It has details about pomo format and stuff.

Sorry for accidentally close this

**Comment by HynDuf** [comment]
It's been a while so I'll close it.
